services:
  app:
    build: .
    container_name: "subscription_manager"
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ".env"
    restart: unless-stopped

  postgres:
    container_name: "subscription_manager_db"
    image: postgres:14-alpine
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge